name: Deploy Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "jupyter-book>=2.0.0a0"  # or your required version
          pip install typst  # if needed for PDF export
          pip install ghp-import
          pip install mystmd

      - name: Build Jupyter Book with BASE_URL
        run: |
          cd book
          BASE_URL=/sensingsoundandmusic myst build --html

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f book/_build/html